[package]
name = "tag-std"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cargo-tag-std"
path = "src/bin/cargo_tag_std.rs"

[dependencies]

[package.metadata.rust-analyzer]
# nightly-2025-04-21-x86_64-unknown-linux-gnu
rustc_private = true
