[package]
name = "safety-tool-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
safety-tool-macro = { path = "../safety-tool-macro" }
safety-tool-parser = { path = "../safety-tool-parser" }

[dev-dependencies]
expect-test = "1.5.1"
