name: Aggregate

on:
  workflow_run:
    workflows: [Tests, Rust-for-Linux, Asterinas]
    types: [completed]

jobs:
  ok:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.name != 'Aggregate'
    steps:
      - run: echo "All upstream workflows finished successfully"
