name: Run Tests

on:
  push:
    branches:
  pull_request:
    branches:
env:
  # deploy demo doc
  DOC: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@nightly

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-expand

      - name: Install specified toolchain
        working-directory: safety-tool
        run: |
          rm -f rust-toolchain.toml
          ./gen_rust_toolchain_toml.rs std
          rustup show

      - name: Run Tests
        working-directory: safety-tool
        run: bash run.sh

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        if: env.DOC == 'true'
        with:
          path: safety-tool/tests/basic/target/doc/

  # Deployment job
  deploy:
    if: env.DOC == 'true'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    needs: build
    steps:
      - name: Deploy to GitHub Pages
        if: runner.os == 'Linux' && runner.arch == 'X64' && github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4

