name: Run Tests

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@nightly

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-expand

      - name: Install specified toolchain
        working-directory: safety-tool
        run: |
          rm -f rust-toolchain.toml
          ./gen_rust_toolchain_toml.rs std
          rustup show

      - name: Run Tests
        working-directory: safety-tool
        run: bash run.sh

