name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  verify-rust-std:
    uses: ./.github/workflows/verify-rust-std.yml

  rust-for-linux:
    uses: ./.github/workflows/rust-for-linux.yml

  asterinas:
    uses: ./.github/workflows/asterinas.yml

  deploy:
    needs: [tests, rust-for-linux, asterinas]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml

  lsp:
    uses: ./.github/workflows/lsp.yml
