name: Check Rust for Linux

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout tag-std to rust-for-linux branch
        uses: actions/checkout@v4
        with:
          ref: rust-for-linux

      - name: Install deps required by linux
        run: sudo apt-get install libelf-dev

      - name: Install safety-tool
        run: cd safety-tool && cargo install --path . --locked

      - name: Download Linux Repo
        run: .github/rust-for-linux/install.sh

      - name: make version
        run: make -v

      - name: Check Linux Repo
        run: .github/rust-for-linux/check.sh

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: linux/Documentation/output/rust/rustdoc/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    needs: check
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
